# make tmux display things in 256 colors
set -g default-terminal "xterm-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# set scrollback history to 10000 (10k)
set -g history-limit 10000

# Set Escape Key Timer to 1 Second
set -sg escape-time 1

# Adding index to start at 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Set the status bar (bottom of screen) color
set-option -g status-bg colour183 # Set Colour to light purple
set-option -g status-fg colour232 # Set Colour to black


# Use vim style keys in copy mode
set-window-option -g mode-keys vi
set -g mouse on